### ISSUE TITLE
Functionality list for redesign

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq.github.io#29]
Functionality list to guide wireframe creation.

- Functionality
  - **Bulk download across variables such as location, city, country, pollutant and date**
  - Some way to group locations/cities/countries into groupings based on averages
  - Comparison tool in chart form (compare everything vs everything for selectable locations/cities/countries)
  - **Map visualization allowing selection between different pollutants and potentially between different sensor types**
  - **List view showing all data locations (maybe this is how we start data downloads?) with more source information?**

- Pages
  - Individual location/city/country pages
  - General air quality info page
  - Process/data model info page
  - **Get involved page (provide translations, make/maintain adapters, build things with API)**
  - Adapter status page (last time successfully run, link to code?)
  - API use case/examples page
  - Stories/narratives page (may be the same as one above?)

- Potential stories/visualizations
  - Map with time slider but where all time values are set to local time, could be cool!

Items in bold will be focused on first. If there are more items to get on the list, leave a comment and I'll update the list.

cc/ @olafveerman @smit1678 @RocketD0g @ascalamogna

**Comment by RocketD0g** [comment]
This is so AWESOME. And the bolded items are right on target.

The only thing I would add as a priority item in terms of functionality is
the ability to input a specified time interval and output an average
pollutant value. This is something GBD folk have specifically mentioned as
valuable to them, and one that would likely interest those in policy
arenas.

I do think this (or the visualizations) will be non-trivial, as it will
require a pruning of 'good' vs. 'bad' data (e.g. does '0' mean '0'? or no
data?). @jflasher - I'm thinking of the poor data outputs we saw with the
top 10 most polluted places observed on the twitter feed.



On Wed, Oct 7, 2015 at 6:19 PM, Joe Flasher <notifications@github.com>
wrote:

> Functionality list to guide wireframe creation.
>
>    -
>
>    Functionality
>    - *Bulk download across variables such as location, city, country,
>       pollutant and date*
>       - Some way to group locations/cities/countries into groupings based
>       on averages
>       - Comparison tool in chart form (compare everything vs everything
>       for selectable locations/cities/countries)
>       - *Map visualization allowing selection between different
>       pollutants and potentially between different sensor types*
>       - *List view showing all data locations (maybe this is how we start
>       data downloads?) with more source information?*
>    -
>
>    Pages
>    - Individual location/city/country pages
>       - General air quality info page
>       - Process/data model info page
>       - *Get involved page (provide translations, make/maintain adapters,
>       build things with API)*
>       - Adapter status page (last time successfully run, link to code?)
>       - API use case/examples page
>       - Stories/narratives page (may be the same as one above?)
>    -
>
>    Potential stories/visualizations
>    - Map with time slider but where all time values are set to local
>       time, could be cool!
>
> Items in bold will be focused on first. If there are more items to get on
> the list, leave a comment and I'll update the list.
>
> cc/ @olafveerman <https://github.com/olafveerman> @smit1678
> <https://github.com/smit1678> @RocketD0g <https://github.com/RocketD0g>
> @ascalamogna <https://github.com/ascalamogna>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaq/openaq.github.io/issues/29>.
>



-- 

507.246.2097

**Comment by jflasher** [comment]
I wonder if we should do the averaging and such server side and pass the result via the API or let it be handled client side? Doing it client-side would keep these assumptions out of the API, which seems appealing.

**Comment by ascalamogna** [comment]
I've been working on a basic site map and some wireframes of the downloading system. 

Here is the site map, it's easy to add pages, sub pages etc. but I mostly did this so I could get a sense of where you can download from and where you can't.

![openaq_sitemap-01](https://cloud.githubusercontent.com/assets/6752098/10402450/8378b402-6e93-11e5-86f1-2950a86b2333.png)

Here is my logic with how we display information to download. The when you click "sources" in the navigation, you will be taken to the table of sources. 

![download_stystem-03](https://cloud.githubusercontent.com/assets/6752098/10402737/1bf7640c-6e95-11e5-9391-6cc8a289f84b.png)

This page has primary features up top, including a download all, and a link to the separate filtered download page that allows for more specific, customized data downloading. In order to make this page more usable and scalable. I've added a continent drop down and a search feature. The search feature would allow you to search for anything, continent, country, city, location, etc. The continent feature is a drop down where you can select a continent to explore, the page would be reordered so that continent is at the top. 

![download_stystem-01](https://cloud.githubusercontent.com/assets/6752098/10402731/161ce21e-6e95-11e5-9412-163ed98d5947.png)


The filtered download page allows a user to select different levels of data. They can stop at any point. For example, it wouldn't be required to pick a pollutant or even a city. A summary of what the user has selected is displayed by the download button for their selections at the bottom of the page. There's also the option to add another location to a users filtered download. I thought this would be helpful if you wanted to do a specific timeframe for several cities, or locations. When you click that button you can either choose to have the same filters already selected autofill for the additional location or you can choose different ones. 

I think this functionality solves a couple of problems.

Problem: We want the user to know how much data is available but listing everything in one huge table is difficult to navigate. It's also important to have data displayed this way for someone who is not entirely sure what they are looking for. This view is more for someone who is interested in exploring our data. 

Solution: We two options for navigating this table. The first is by continent. I'm open to suggestions for something else but I felt we needed a "regional" way to search through countries and this was most logical. The second option is a search feature. This functionality allows someone to quickly see if we have a country or not. It also is useful to someone who knows a lot about locations and to someone who knows nothing. 

Problem: There's a lot of data and some users may want to filter before downloading while other users would rather filter and explore a larger data set. 

Solution: The table view allows the user to download, continent, country and city datasets. The filtered download page allows users to drill down and download exactly what they would like to see. This is great for someone who has a specific place in mind, while the larger downloads cater to people exploring.

Additional notes, if we have country pages for each country, click on the country within the table would take you to that page. We could include an additional download button here.

This is just a good starting point, so I'd love feedback and any other suggestions you might have or download needs that should be addressed!

**Comment by ascalamogna** [comment]
Also, these aren't the most developed wireframes, I just wanted to try and figure out a general flow for finding and downloading data, so any feedback on that is key.

**Comment by olafveerman** [comment]
These look great. I especially like the 'guided' download that gives the user a high degree of control over the data.

Regarding the sources list:

1. should we name the main menu item 'Data' ? This section seems to encompass much more than just the sources
2. between country and location, there is one more level, which is the source. In the Australian example, we have a source that reports on 20 something locations from New South Wales. I can imagine that in the future, we might get more data for Australia, but from another source.  
Do we want to expose this distinction to the user as well?
3. attribution is an important one. If we decide not to include sources in the hierarchy, we need to find a good place to store this information. This would be the name of the organization, linking to the page.
4. do we want to entertain the thought of creating a dedicated source / country page? This way we would keep the main sources/data page clean, and provide detail on those pages.

**Comment by ascalamogna** [comment]
@olafveerman I'm not sure if we're talking about the same thing, but referring to your #2 the rest of the locations would be listed in the empty part of the table. Does the location have the source title? For example for Brazil everything listed in cards could go in the table "Americana, Araraquara" etc, does that convey the source? I think I might be confusing location and source here?

I think an attribution page would be nice, unless there's a way to incorporate the attribution into the table through a hover or link etc. I will look into it. I hate to add to much to the table, since there is already so  much data and so many layers.

**Comment by ascalamogna** [comment]
@olafveerman @jflasher @smit1678 

What do we think of this to replace the table view from above? It'll list all of our sources and be filterable by country and each source can be expanded to see the locations. Then any country, continent or city filtering can be done with the filter download page. This way we do have all of the data listed in one place, but it's expandable in places so we can cut down on the length of the page, and it's still filterable. Does country make sense for this? I figured each source would have to be in a country. When you filter those sources move to the top, and the rest are still listed below. This allows for multiple sources from one country too. 

As far as navigation, I think the sources tab in the navigation will lead to this page, but we can also add a dropdown under there to the filtered download as well as have the button on this page as well. 

![download_stystem-04](https://cloud.githubusercontent.com/assets/6752098/10433815/09919580-70e3-11e5-83de-9a71bf381f30.png)

**Comment by RocketD0g** [comment]
Hi Anna - this looks fantastic! I think the country-level makes total
sense. I think we may have issues with some stations when filtering by
city, as a few cases (not even sure if we have them yet), there will be
rural sites and for others it may be hard to define what falls in a
particular city or not.

What do others think?

I believe this was brought up last week by someone, but how do people feel
about changing 'Sources' to 'Data'? This page is really about getting data
more than listing sources, yeah?



On Mon, Oct 12, 2015 at 1:17 PM, Anna <notifications@github.com> wrote:

> @olafveerman <https://github.com/olafveerman> @jflasher
> <https://github.com/jflasher> @smit1678 <https://github.com/smit1678>
>
> What do we think of this to replace the table view from above? It'll list
> all of our sources and be filterable by country and each source can be
> expanded to see the locations. Then any country, continent or city
> filtering can be done with the filter download page. This way we do have
> all of the data listed in one place, but it's expandable in places so we
> can cut down on the length of the page, and it's still filterable. Does
> country make sense for this? I figured each source would have to be in a
> country. When you filter those sources move to the top, and the rest are
> still listed below. This allows for multiple sources from one country too.
>
> As far as navigation, I think the sources tab in the navigation will lead
> to this page, but we can also add a dropdown under there to the filtered
> download as well as have the button on this page as well.
>
> [image: download_stystem-04]
> <https://cloud.githubusercontent.com/assets/6752098/10433815/09919580-70e3-11e5-83de-9a71bf381f30.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaq/openaq.github.io/issues/29#issuecomment-147466408>
> .
>



-- 

507.246.2097

**Comment by jflasher** [comment]
I really like the layout of this table, but I think I liked the geo focus (continent->country->city->location) of the other version. I had always thought about trying to make icons for the different pollutants and coloring them in if they were present and graying them out if they weren't. Also, in general, I think maybe we should try and downplay the concept of sources. They're a technical necessity, but I don't know that they provide a lot of information to a person visiting the site. Might make sense to design this as if we only had one mega source that gave us everything.

A couple of tricky things will be that a source doesn't necessarily only provide data for one country (it does currently, but doesn't need to). Also, the system is ultimately focused on measurements. What I mean by that is that a location might have 4 different parameters it's measuring and those 4 measurements might have different time resolutions and different last updated dates, which could be misrepresented in this format. This is similar to the way we do it on the current sources page, but we've got more examples of where it breaks now. :sob: Maybe we could stick with this format and show the time resolution and last updated time on hover? I guess we could still show the last time the location was updated, regardless of source, that's probably still useful.

**Comment by olafveerman** [comment]
Not sure if I totally agree with @jflasher on downplaying the sources. Attribution is important and we should look for a way to expose it.
Also, might there be some semantic confusion here? I think we use source for the organization that should receive attribution, and source as in the API endpoint / HTML table etc.

**Comment by ascalamogna** [comment]
After some discussion today, I've come up with the following wireframes that I think meet our data and source needs in addition to the filtered download page. I've done two separate pages one for data downloading, sorted/filtered by geography, and another sources pages, that focuses on the actually sources of the data. I think this is the most clear for users and really caters to the needs of the users. 

The sources pages is a list of expandable tables in alphabetically order by source. Here we can also add info about our sources, an option to add or suggest a source (or whatever sort of call to actions we'd like to associate with sources) and search feature since post people using this page will already have a source in mind.

![download_stystem-09](https://cloud.githubusercontent.com/assets/6752098/10438852/20952ce4-7104-11e5-81c9-f7943c567d7a.png)

The data page is a cleaner version of the initial data page that uses the ux from second wireframe iteration. The scale would be applied to each pollutant box to give some quick visual information about the latest measurement. On hover, you can see the resolution and latest report.

![download_stystem-08](https://cloud.githubusercontent.com/assets/6752098/10438853/249b8978-7104-11e5-9628-f50acf23df2a.png)

@olafveerman @smit1678 @RocketD0g @jflasher

**Comment by jflasher** [comment]
@ascalamogna this is looking great! I like the way we're handling showing the data slightly different based on the sources or data view. And I think the pollutant level readings over a whole bunch of locations could look very nice. 

It makes me think I should change this https://api.openaq.org/v1/locations to output just a list of locations similar to https://api.openaq.org/v1/locations and then we can group them however we want on the frontend.

**Comment by danielfdsilva** [comment]
V2 ready
